pip install numpy

In [8]:
import numpy as np

In [9]:
n1 =np.array([1,2,3,4])
print(n1)
print(type(n1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
n1.shape

(4,)

In [13]:
n2=np.array([[1,2,3,4],[1,3,6,6]])
print(n2)
print(n2.shape)

[[1 2 3 4]
 [1 3 6 6]]
(2, 4)


creating matrix
-arange
-linscape
-random.rand
-random.randn
-eye
-ones
-zeros

In [14]:
x=np.arange(-10,-10,.2)
x.shape

(0,)

In [18]:
y=np.linspace(1,5,10)
print(y)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [19]:
np.random.rand(3,3)

array([[0.52258647, 0.6047782 , 0.52294769],
       [0.28704611, 0.15625112, 0.53149393],
       [0.64731156, 0.50942553, 0.96093321]])

In [20]:
np.random.randn(10)

array([-1.74785681, -0.52626774, -1.05339109, -0.35943518,  1.32769052,
        0.21092347, -0.35069385, -0.1595514 ,  0.04010112, -1.56324878])

In [26]:
x=np.random.randint(1,10,(3,2))
y=np.random.randint(1,10,(3,2))
print(x)
print(y)

[[5 1]
 [7 3]
 [2 7]]
[[2 1]
 [6 7]
 [2 7]]


In [27]:
x+5

array([[10,  6],
       [12,  8],
       [ 7, 12]])

In [28]:
x/y

array([[2.5       , 1.        ],
       [1.16666667, 0.42857143],
       [1.        , 1.        ]])

In [29]:
x*y

array([[10,  1],
       [42, 21],
       [ 4, 49]])

In [30]:
x.dot(y)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [33]:
np.sin(x)


array([[-0.95892427,  0.84147098],
       [ 0.6569866 ,  0.14112001],
       [ 0.90929743,  0.6569866 ]])

In [34]:
print(x.sum())
print(x.mean())
print(x.std())


25
4.166666666666667
2.3392781412697


In [36]:
a=np.linspace(0,5,50)
print(a.shape)
a2=a.reshape(10,5)
print (a2)
print(a2.shape)

(50,)
[[0.         0.10204082 0.20408163 0.30612245 0.40816327]
 [0.51020408 0.6122449  0.71428571 0.81632653 0.91836735]
 [1.02040816 1.12244898 1.2244898  1.32653061 1.42857143]
 [1.53061224 1.63265306 1.73469388 1.83673469 1.93877551]
 [2.04081633 2.14285714 2.24489796 2.34693878 2.44897959]
 [2.55102041 2.65306122 2.75510204 2.85714286 2.95918367]
 [3.06122449 3.16326531 3.26530612 3.36734694 3.46938776]
 [3.57142857 3.67346939 3.7755102  3.87755102 3.97959184]
 [4.08163265 4.18367347 4.28571429 4.3877551  4.48979592]
 [4.59183673 4.69387755 4.79591837 4.89795918 5.        ]]
(10, 5)


In [37]:
a2.reshape(5,5,2)

array([[[0.        , 0.10204082],
        [0.20408163, 0.30612245],
        [0.40816327, 0.51020408],
        [0.6122449 , 0.71428571],
        [0.81632653, 0.91836735]],

       [[1.02040816, 1.12244898],
        [1.2244898 , 1.32653061],
        [1.42857143, 1.53061224],
        [1.63265306, 1.73469388],
        [1.83673469, 1.93877551]],

       [[2.04081633, 2.14285714],
        [2.24489796, 2.34693878],
        [2.44897959, 2.55102041],
        [2.65306122, 2.75510204],
        [2.85714286, 2.95918367]],

       [[3.06122449, 3.16326531],
        [3.26530612, 3.36734694],
        [3.46938776, 3.57142857],
        [3.67346939, 3.7755102 ],
        [3.87755102, 3.97959184]],

       [[4.08163265, 4.18367347],
        [4.28571429, 4.3877551 ],
        [4.48979592, 4.59183673],
        [4.69387755, 4.79591837],
        [4.89795918, 5.        ]]])

In [38]:
m=np.ramdom.randint(1,10(10,10))
print(m)

<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
C:\Users\srish\AppData\Local\Temp\ipykernel_15760\1792810548.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  m=np.ramdom.randint(1,10(10,10))
C:\Users\srish\AppData\Local\Temp\ipykernel_15760\1792810548.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  m=np.ramdom.randint(1,10(10,10))
C:\Users\srish\AppData\Local\Temp\ipykernel_15760\1792810548.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  m=np.ramdom.randint(1,10(10,10))


AttributeError: module 'numpy' has no attribute 'ramdom'

In [39]:
print(m[0,0])
print(m[0-1])
print(m[-1,0])
print(m[-1,-1])


NameError: name 'm' is not defined

In [40]:
print(m[0])
print(m[1])
print(m[-1])
print(m[-1])
print(m[:3])
print(m[-3:])


NameError: name 'm' is not defined

In [ ]:
print(m[:,[0,2,3]])


filtering

In [ ]:
m < 5#boolean filter


In [ ]:
m[m<5]


NameError: name 'm' is not defined

In [ ]:
m[m>3]

NameError: name 'm' is not defined

In [ ]:
m[(m>=3)&(m<=3)]


NameError: name 'm' is not defined